- name: Instalar y configurar Apache
  hosts: local
  become: true
  tasks:
    - name: Instalar apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Asegurarse de que apache2 está iniciado
      service:
        name: apache2
        state: started
        enabled: true

    - name: Crear página de prueba
      copy:
        dest: /var/www/html/index.html
        content: "<h1>¡Apache instalado con Ansible!</h1>"
        owner: root
        group: root
        mode: '0644'
