---
- name: Instalar y configurar Apache (Ubuntu/Debian)
  hosts: localhost # Lo ajusto a localhost para que funcione fácilmente en el Docker
  become: true
  tasks:
    - name: Actualizar caché de paquetes
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar Apache HTTP Server
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Iniciar y habilitar el servicio Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true